"""add_holdings_table

Revision ID: 9660eb130f5a
Revises: b38be613786e
Create Date: 2026-03-22 13:48:26.028750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9660eb130f5a'
down_revision: Union[str, None] = 'b38be613786e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_denom', sa.String(length=128), nullable=False),
    sa.Column('token_symbol', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('avg_price_usd', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
