"""add_account_funding_table

Revision ID: b38be613786e
Revises: 561f8b003c04
Create Date: 2026-03-22 13:47:31.698145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38be613786e'
down_revision: Union[str, None] = '561f8b003c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_fundings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('paystack_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_fundings_reference'), 'account_fundings', ['reference'], unique=True)
    op.create_index(op.f('ix_account_fundings_user_id'), 'account_fundings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_fundings_user_id'), table_name='account_fundings')
    op.drop_index(op.f('ix_account_fundings_reference'), table_name='account_fundings')
    op.drop_table('account_fundings')
    # ### end Alembic commands ###
