"""initial_schema

Revision ID: fbc4bc23de4d
Revises: 
Create Date: 2026-03-22 11:53:04.284925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc4bc23de4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('wallet_type', sa.String(length=32), nullable=False),
    sa.Column('expo_push_token', sa.String(length=255), nullable=True),
    sa.Column('preferred_currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.create_table('price_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_denom', sa.String(length=128), nullable=False),
    sa.Column('token_symbol', sa.String(length=32), nullable=False),
    sa.Column('target_price_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('condition', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('onramp_provider', sa.String(length=32), nullable=False),
    sa.Column('onramp_order_id', sa.String(length=128), nullable=False),
    sa.Column('fiat_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fiat_currency', sa.String(length=10), nullable=False),
    sa.Column('fiat_status', sa.String(length=32), nullable=False),
    sa.Column('inj_amount', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('inj_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_denom', sa.String(length=128), nullable=False),
    sa.Column('target_token_symbol', sa.String(length=32), nullable=False),
    sa.Column('swap_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('swap_status', sa.String(length=32), nullable=False),
    sa.Column('swap_amount_received', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('swap_slippage_tolerance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_onramp_order_id'), 'transactions', ['onramp_order_id'], unique=True)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_denom', sa.String(length=128), nullable=False),
    sa.Column('token_symbol', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token_denom', name='uix_user_token_watchlist')
    )
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_onramp_order_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
